on:
  workflow_dispatch:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"

jobs:
  update_site:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github Repo Action
        uses: sudosubin/git-clone-action@v1.0.1
      - name: Git Clone Action
        # You may pin to the exact commit or the version.
        # uses: sudosubin/git-clone-action@8a93ce24d47782e30077508cccacf8a05a891bae
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          # Repository owner and name. Ex: sudosubin/git-clone-action
          repository: konachan100/konachan100-src # optional, default is ${{ github.repository }}
          # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
          platform: github # optional, default is github
          # Git branch or tag to checkout.
          #ref: # optional
          # Relative path from current directory, where to clone.
          path: src # optional
      - name: pwd
        run: pwd
      - name: show contents
        run: tree .
      - name: update site
        run: bash update.sh
