on:
  workflow_dispatch:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"

jobs:
  update_site:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github Repo Action
        uses: sudosubin/git-clone-action@v1.0.1
      - name: pwd
        run: pwd
      - name: show contents
        run: tree .
      - name: update site
        run: bash update.sh
