on:
  workflow_dispatch:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"

jobs:
  update_site:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Github Repo Action
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          # Repository Owner
          owner: konachan100
          # Repository name
          repository: konachan100.github.io
          # PAT with repository scope (https://github.com/settings/tokens)
          access-token: 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
      - name: show contents
        run: tree .
      - name: ll
        run: ls -l
      - name: cd
        run: cd konachan100.github.io
      - name: update site
        run: bash update.sh
