on:
  workflow_dispatch:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"

jobs:
  update_site:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: git clone git@github.com:konachan100/konachan100.github.io.git
      - name: cd
        run: cd konachan100.github.io
      - name: show contents
        run: tree .
      - name: update site
        run: bash update.sh
